### PR TITLE
First attempt to fill the index of Admin Corner (issue #64)

### PR DESCRIPTION
**Pull request by oinizan**
- This is a first attemp, a lot of content is taken from the galaxy wiki
- We plan to substitute the text of "By Default Galaxy" and "Galaxy in production, basic configuration" with figures (tomorrow ...)
Cheers,

Olivier & Valentin

### CODE REVIEW

**Comment by bgruening** [comment]
@oinizan like it! Do you want me to merge it or should I keep it open and you work on it tomorrow?

**Comment by oinizan** [comment]
@bgruening thanks, keep it open, we work on it tomorrow. Thanks !

**Comment by ValentinMarcon** [comment]
We added the figures, and we made the link with the next tutorial Cf. [issue123](https://github.com/bgruening/training-material/issues/123).

**Comment by bgruening** [comment]
Thanks! Please remove the label work-in-progress if you think we should review it!
Great stuff!!

**Comment by hrhotz** [comment]
is this pull request still valid? looks like it has been superseeded by PR #127, hasn't-t?

**Comment by oinizan** [comment]
Yes, this is the PR# 127 now.

**Pull request merged**
