### PR TITLE
Start reorganization of Admin corner

### PR DESCRIPTION
**Pull request by bebatut**
Hi,

I started the reorganization of `Admin corner` directory.

To do:
- [ ] Move the [current ppt presentation of 10rules](https://github.com/bgruening/training-material/blob/master/staging/10rules_for_GaaS.20160626.pptx) to `reveal.js`
- [ ] Add images
- [ ] Improve the format of the tutorial on db schema
- [ ] Build the Docker image
- [ ] Add a Galaxy tour

Bérénice

### CODE REVIEW

**Comment by bgruening** [comment]
ping @hrhotz  :)

**Comment by hrhotz** [comment]
--- hrhotz ping statistics   ;) ---
5 packets transmitted,0 received, 100% packet loss, time 3999ms
rtt min/avg/max/mdev = 0.144/0.174/0.227/0.032 ms

...maybe after my vacation and/or as part of the prep for #SG2016T  ?

**Comment by bebatut** [comment]
I think it is ready for merge :)

**Comment by bgruening** [comment]
Looks solid to me! Thanks a lot!

**Pull request merged**
