### PR TITLE
fix links and update travis test

### PR DESCRIPTION
**Pull request by shiltemann**

### CODE REVIEW

**Comment by shiltemann** [comment]
hmm, why did test pass when there are failed urls? ..does it only take exit code of last checked file?

**Comment by bgruening** [comment]
I guess it is this one: http://stackoverflow.com/questions/14871147/how-to-exit-from-find-exec-if-it-fails-on-one-of-the-files

**Comment by shiltemann** [comment]
ok, changed the travis command, it should now fail if any of the files fail, but still always run the check on all of them :) ..and it's also checking html files now

**Comment by bgruening** [comment]
Awesome!

**Pull request merged**
