### PR TITLE
Slides for RNAseq #93

### PR DESCRIPTION
**Pull request by mwolfien**
Hey,
I started to create a slide deck for the RNA-Seq introduction. (That's the progress so far. I restructured the introduction and extended the data processing part. I will put further work on it tomorrow. Feel free to add suggestions and improvements =)

Related to #93

### CODE REVIEW

**Comment by bgruening** [comment]
Let me know if you need a review :)

**Comment by mwolfien** [comment]
I'm at the last slide :D Give me 10 more minutes =)

**Comment by mwolfien** [comment]
Review needed for the RNA-seq intro slides

**Comment by bgruening** [comment]
@mwolfien great work! Can you rebase this branch please?
@bebatut any comments?

**Comment by bebatut** [comment]
@mwolfien Thanks for this.
I will merge your work

**Pull request merged**
