### PR TITLE
Issue 123

### PR DESCRIPTION
**Pull request by oinizan**
This is the first version of the tutorial "From dev instance to production instance".
This pull request gives an overview of the final result.
@bgruening, @bebatut and @hrhotz  what do you think ?
Now, the plan is simple: finsh the tutorial and prepare the docker image (and the html page ?).
Any suggestions ?

### CODE REVIEW

**Comment by bgruening** [comment]
We need a rebase/merge here :)

**Comment by bgruening** [comment]
This looks like a wonderful contribution. Let's wait for @hrhotz to review it. What kind of suggestions do you need? Any help needed?

**Comment by oinizan** [comment]
Questions may be: 
- Are you ok with the workflow of the tutorial ?
(From a "Basis Intallation" to "Disable dev settings" to ... and to finish with a config for production.)
- And do we need to do this because wiki pages already exists ?
(https://wiki.galaxyproject.org/Admin/GetGalaxy and https://wiki.galaxyproject.org/Admin/Config/Performance/ProductionServer)
I think that a tutorial could add some value, in particular with a docker container linked to it.
I also so think that the next tutorial will be "Setting galaxy as a service" and the next one may be "Deploying Galaxy with ansible playbook".
@hrhotz @natefoo Suggestions ? Ideas ?

**Comment by bgruening** [comment]
@tnabtaf can you comment on the Wiki page question. How do you see the GTN, this repo and the wiki coexists?

**Comment by tnabtaf** [comment]
I was avoiding this question....

My thought is that the wiki is a reference manual, and that training material are tutorials.  Yes they are somewhat redundant, but I think the purposes they serve are sufficiently different that the overlap is worth the cost.

My bigger concern (and only tangentially related to this) is that @natefoo, @martenson, and Simon Gladman are currently working on training material for Galaxy Admin Training in November and February, and how that will fit in here.  Should I open that as a separate issue?

**Comment by bgruening** [comment]
@tnabtaf yes please open a new issue. ping @Slugger70

**Comment by bgruening** [comment]
> Questions may be: 
- Are you ok with the workflow of the tutorial ?
(From a "Basis Intallation" to "Disable dev settings" to ... and to finish with a config for production.)

If my opinion counts .... I'm ok with this! :)

> - And do we need to do this because wiki pages already exists ?
(https://wiki.galaxyproject.org/Admin/GetGalaxy and https://wiki.galaxyproject.org/Admin/Config/Performance/ProductionServer)
I think that a tutorial could add some value, in particular with a docker container linked to it.
I also so think that the next tutorial will be "Setting galaxy as a service" and the next one may be "Deploying Galaxy with ansible playbook".
@hrhotz @natefoo Suggestions ? Ideas ?

I think we should not rebuild stuff that is already there but offer links and promote this. The wiki will move to github soon so we can link more easily.
But there is a subtle difference between Wiki and Tutorial imho. A wiki is presenting information in a dense way a tutorial is building knowledge step by step ... so I see here a value. Just my opinion.

**Comment by oinizan** [comment]
"A wiki is presenting information in a dense way a tutorial is building knowledge step by step ... so I see here a value": if my opinion counts, I am completely agree with you.
And, as you probably notice I am ready to finish this tutorial (hackathons are good places to start, hackathon are magic ...) and maybe start new ones ...
But as @tnabtaf  says other initiatives are "on the rails". So maybe we should synchronize each others ...

**Comment by hrhotz** [comment]
I will look at in more details on Monday...what I have seen so far looks great! Thank you very much

**Comment by hrhotz** [comment]
Hi @oinizan 
I am happy to merge...can you just look at the conflict first

**Comment by oinizan** [comment]
Hi @hrhotz 
I have resolved the conflicts via command line.
Let me know

**Comment by hrhotz** [comment]
bizarre, I still have a conflicting file: "Admin-Corner/readme.md"

**Pull request merged**
