### PR TITLE
New Templating of the training material to use only the website

### PR DESCRIPTION
**Pull request by bebatut**
Hi,

To help users of the training material and improve their training experience, I worked on formatting the training material to be mainly based on the website, and not on tutorial rendered GitHub (a bit disturbing with all the buttons when you are not familiar with GitHub). You can have a look at http://bebatut.fr/training-material/ to give you an idea of the new format.

The templating of the tutorial is changed to help highlighting some useful parts (hands-on, questions, ...). I worked on RNA-Seq tutorial as a draft of this: http://bebatut.fr/training-material//RNA-Seq/tutorials/ref_based. Behind it is really similar to previous templates with only markdown for the content. Some metadata and some layouts were just added to wrap the tutorials and make them "beautiful" in a website.

I also changed the slide format to use Remark.js and only markdown to make the slides: http://bebatut.fr/training-material/RNA-Seq/slides/#1

I worked with Jekyll as templating system. I defined different layouts (main page, topic page, tutorial page and slides). I also added several metadata using yaml around the tutorials and the topics to limit the redundancy and help the upkeep. And when we will deploy these materials to a website as the new Galaxy website, it will be easier :)

To help you as contributors, I tried to explain everything in the [CONTRIBUTING.md](https://github.com/bebatut/training-material/blob/master/CONTRIBUTING.md). The structure of the GitHub repository did not really change. Some directories were added for Jekyll. But the structure of the directories of the topics did not change, only a file `index.md` were added. The metadata for each topic is defined in a YAML file in `data` directory.  You can have a look  to my fork to explore the changes: https://github.com/bebatut/training-material

What do you think about this new template? 

Bérénice

### CODE REVIEW

**Comment by bgruening** [comment]
In this PR there are two things and maybe we can split the discussions and reviews into two distinct directions. 

First is the content, the new template and the refreshed Guidelines - I think this is a great improvement and will make things easier for trainers and trainees. The biggest point is probably the removal of the reveal.js slides and sticking to markdown for everything - this was discussed during the hackathon multiple times and I think is a nice way forward.

Second and as a direct consequence of the first is the generation of a website that serves the slides and the content to users via a nice looking website. This is more technical and will probably change again in the near future. We are thinking of using the same mechanism as the new [Galaxy Hub](https://github.com/galaxyproject/galaxy-site) and align with this style and build-system. So jekyll will eventually go away. We discussed this already with @dannon.

I guess at this point it is important to say, that what ever the build system will look like, we want to concentrate more on the content and the first part outlined by @bebatut in this PR - the new template.

**Comment by shiltemann** [comment]
will make some time to look at this in more detail soon, but looks great @bebatut! love the way the tutorials look on the website :)

**Comment by bebatut** [comment]
@shiltemann Sure. It is still a WIP...

**Comment by abretaud** [comment]
> What do you think about this new template?

It looks very nice! 👏

**Comment by bgruening** [comment]
:tada:

**Comment by shiltemann** [comment]
awesome \o/

**Pull request merged**
